# 线性代数

## 标量

In [1]:
import torch

# 只有一个元素的向量
x = torch.tensor([1.0])
y = torch.tensor([3.0])
x+y,x*y,x/y,x**y

(tensor([4.]), tensor([3.]), tensor([0.3333]), tensor([1.]))

## 向量

向量点积：对应元素相乘再相加；  

In [20]:

x = torch.tensor([5.0,4.0,3.0,2.0,1.0])
y = torch.arange(5,dtype=torch.float32)
x,len(x),x.shape

(tensor([5., 4., 3., 2., 1.]), 5, torch.Size([5]))

In [22]:
# 向量点积
torch.dot(x,y),torch.sum(x*y)

(tensor(20.), tensor(20.))

## 矩阵

对称转置等于本身；
矩阵运算：
* 矩阵相乘：两个矩阵阶数一直，对应元素相乘；$C = A * B -> c_{i,j} = a_{i,j} * b_{i,j} $
* 矩阵数乘：矩阵每个元素乘以数值；

In [11]:
A = torch.arange(12).reshape(4,3)  # 二维矩阵
B = torch.arange(24).reshape(2,3,4) # 三维矩阵
A,A.T

(tensor([[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]),
 tensor([[ 0,  3,  6,  9],
         [ 1,  4,  7, 10],
         [ 2,  5,  8, 11]]))

In [13]:
C = B.clone()   # 重新分配内存
C,id(C) == id(B)

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 False)

In [19]:
B = A * A      # 矩阵乘法，对应元素相乘；
asum = A.sum() # 所有元素相加
asum0 = A.sum(axis=0) # 按照第一维度求和，a0 = a0j相加
asumx = A.sum(axis=0, keepdims=True) # 求和之后保留阶数
B,asum,asum0,asumx

(tensor([[  0,   1,   4],
         [  9,  16,  25],
         [ 36,  49,  64],
         [ 81, 100, 121]]),
 tensor(66),
 tensor([18, 22, 26]),
 tensor([[18, 22, 26]]))

# 微积分

## 标量导数
$f'(x) = y' = \frac{dy}{dx} = \frac{df}{dx} = \frac{d}{dx}f(x) = Df(x) = D_{x}f(x) $  其中$\frac{d}{dx}$和$D$是微分运算符，表示微分操作。
* $DC$ = 0 ($C$ 是一个常数）、
* $Dx^{n} = nx^{n-1}$ （$n$ 是任意实数）
* $De^{x} = e^{x}$
* $Dln(x) = \frac{1}{x}$

运算法则：
* 常数相乘： $\frac{d}{dx}\left[ Cf(x) \right] = C\frac{d}{dx}f(x) $
* 加法法则：$\frac{d}{dx}\left[f(x) + g(x)\right] = \frac{d}{dx}f(x) + \frac{d}{dx}g(x)$
* 乘法法则：$\frac{d}{dx}\left[f(x)g(x)\right] = f(x)\frac{d}{dx}\left[g(x)\right] + g(x)\frac{d}{dx}\left[f(x)\right]$
* 除法法则：$\frac{d}{dx}\left[\frac{f(x)}{g(x)}\right] = \frac{g(x)\frac{d}{dx}\left[f(x)\right] - f(x)\frac{d}{dx}\left[g(x)\right]}{\left[g(x)\right]^{2}}$

### 偏导数
设$y = f(x_{1},x_{2}, ... , x_{n})$是一个具有$n$个变量的函数。$y$关于第$i$个参数$x_{i}$的偏导数为：
$$\frac{\partial y}{\partial x_{i}} = \underset{h->0}{lim}\frac{f(x_{1},x_{2},...,x_{i}+h,...,x_{n}) - f(x_{1},...,x_{i},...,x_{n})}{h}$$
计算时将除了$x_{i}$之外的变量视为常数；

### 梯度
多元函数偏导数组成的向量，即该函数的梯度向量。设函数$f:\mathbb{R}^{n} -> \mathbb{R}$的输入是一个n维向量 $\mathbf{x} = [x_{1},x_{2},...,x_{n}]^\top$，并且输入是一个标量。函数$f(\mathbf{x})$相对于$\mathbf{x}$的梯度是一个包含$n$个偏导数的向量：
$$\nabla _{x}f(\mathbf{x}) = \left[\frac{\partial f(\mathbf x)}{\partial x_{1}}, \frac{\partial f(\mathbf x)}{\partial x_{2}},...,\frac{\partial f(\mathbf x)}{\partial x_{n}}\right]^\top$$

假设$\mathbf{x}$n$维向量：  

* 对于所有$\mathbf{A} \in \mathbf{R}^{m \times n}$，都有$\nabla _{x}\mathbf{Ax} = \mathbf{A}^\top$
* 对于所有$\mathbf{A} \in \mathbf{R}^{n \times m}$，都有$\nabla _{x}\mathbf{x}^\top\mathbf{A} = \mathbf{A}$
* 对于所有$\mathbf{A} \in \mathbf{R}^{n \times n}$，都有$\nabla _{x}\mathbf{x}^\top\mathbf{Ax} = \left(\mathbf{A} + \mathbf{A}^\top \right)\mathbf{x}$
* $\nabla _{x} \lVert x \rVert^{2} = \nabla _{x} \mathbf{x^\top x} = 2\mathbf{x} $

### 链式法则

## 向量导数

In [ ]:
# 绘图
import matplotlib


In [27]:
# 函数定义
def f(x):
    return 3 * x **2 - 4 * x
# 函数导数
def numerical_lim(f,x,h):
    return (f(x+h) - f(x)) / h
# 求x=1时的导数，无限接近于2
h = 0.1
for i in range(5):
    print(f'h={h:.5f}, numerical_lim={numerical_lim(f,1,h): .5f}')
    h*= 0.1

h=0.10000, numerical_lim= 2.30000
h=0.01000, numerical_lim= 2.03000
h=0.00100, numerical_lim= 2.00300
h=0.00010, numerical_lim= 2.00030
h=0.00001, numerical_lim= 2.00003


In [4]:
# 计算y关于x的梯度计算
x = torch.arange(4.0, requires_grad=True)
x.requires_grad_(True)
x.grad  # 获取计算梯度结果
y = 2 * torch.dot(x,x)
y.backward()
x.grad ,y

x.grad.zero_() # 清除之前梯度结果

tensor([0., 0., 0., 0.])

### 自动微分

深度学习框架通过自动计算导数，即自动微分来加快求导。自动微分使系统能够随后反向传播梯度。 这里，反向传播意味着跟踪整个计算图，填充关于每个参数的偏导数。

$y = 2\mathbf{x}^\top\mathbf{x}$ 关于向量$\mathbf{x}$求导

当y不是标量时，向量y关于向量x的导数的最自然解释是一个矩阵。 对于高阶和高维的y和x，求导的结果可以是一个高阶张量。



In [23]:
import torch

x = torch.arange(4.0)
x.requires_grad_(True)
# x.torch.arange(4,requires_grad=True)
y = 2 * torch.dot(x,x)
y.backward() # 反向传播求导
x.grad == 4 * x

# 在默认情况下，PyTorch会累积梯度，我们需要清除之前的值
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

#### 分离计算
有时，我们希望将某些计算移动到记录的计算图之外。 例如，假设y是作为x的函数计算的，而z则是作为y和x的函数计算的。 想象一下，我们想计算z关于x的梯度，但由于某种原因，希望将y视为一个常数， 并且只考虑到x在y被计算后发挥的作用。

这里可以分离y来返回一个新变量u，该变量与y具有相同的值， 但丢弃计算图中如何计算y的任何信息。 换句话说，梯度不会向后流经u到x。 因此，下面的反向传播函数计算 $z=u*x$ 关于x的偏导数，同时将u作为常数处理， 而不是 $z=x*x*x$ 关于x的偏导数。

In [24]:
# 对非标量调用backward需要传入一个gradient参数，该参数指定微分函数关于self的梯度。
x.grad.zero_()
y = x * x
y.backward(torch.ones(len(x)))
x.grad,y,x

# 分离计算
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x
z.backward(torch.ones(len(x)))
x.grad,z,x,u  # 注意导数并不是 3x^2 而是u的值即x^2

x.grad.zero_()
y.sum().backward() # 等价于 y.backward(torch.ones(len(x)))
x.grad == 2 * x

tensor([True, True, True, True])

#### 函数梯度

使用自动微分的一个好处是： 即使构建函数的计算图需要通过Python控制流（例如，条件、循环或任意函数调用），我们仍然可以计算得到的变量的梯度。 



In [29]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()
a.grad,a

(tensor(102400.), tensor(-1.2623, requires_grad=True))

# 概率


**计算均值**：首先计算张量中所有元素的平均值（mean），对于一个多维张量，这通常意味着将所有维度上的元素加总后除以元素总数；

**计算偏差平方和**：对于张量中的每一个元素，计算该元素与均值之间的差，然后将这个差值平方，并对所有的这些平方值求和；

**方差**：将偏差平方和除以元素总数（样本标准差元素个数需要减一）；

**标准方差**：将**方差**开根号；

概率（probability）可以被认为是将集合映射到真实值的函数。在给定的样本空间$S$中，事件$A$的概率，表示为$P\left(A\right)$，满足以下属性：
* 对于任意事件$A$，其概率非负，即$P\left(A\right) \ge 0$
* 整个样本空间的概率为1，即$P(S) \eq 1$
* 对于互斥事件（对于所有$i \ne j$都有$A_{i} \cap B_{j} = 0$）的任意序列$A_{1},A_{2},\dot$发生的概率为它们各自发生的概率之和，即$P\left(\bigcup_{i=1}^{\infty}A_{i}\right) = \sum_{i=1}^{\infty}P\left(A_{i}\right)$

离散（discrete）随机变量（如骰子的每一面） 和连续（continuous）随机变量（如人的体重和身高）之间存在微妙的区别。

## 随机变量

* **联合概率**：给定任意值$a$和$b$，$P(A = a, B = b) \le P(A = a)$
* **条件概率**：$0 \le \frac{P(A=a, B=b)}{P(A=a)} \le 1$ 即$P(B = b| A = a)$，以$A=a$为前提下$B=b$发生的概率
* **贝叶斯定理**：$P(A,B) = P(B|A)P(A) = P(A|B)P(B)$ 当 $P(B) \gt 0$ 时有 $P(A|B) = \frac{P(B|A)P(A)}{P(B)}$
* **边际化**：$P(B) = \underset{A}{\sum}P(A,B)$
* **独立性**：$P(A,B) = P(A)P(B)$


## 期望和方差

 一个随机变量$X$的期望表示为：$E\left[X\right] = \underset{x}{\sum}xP(X = x)$
 当函数$f(x)$的输入是分布$P$中抽取的随机变量时，$f(x)$期望为：$E_{x~P} = \underset{x}{\sum}f(x)P(x)$
 
 衡量随机变量$X$与期望值的偏置，方差：$Var[X] = E[(X - E[X])^2] = E[X^2] = E[X]^2$
 
 方差的平方根被称为标准差

In [30]:
import torch
from torch.distributions import multinomial
from d2l import torch as d2l

fair_probs = torch.ones([6]) / 6  # 概率分布
counts = multinomial.Multinomial(1000, fair_probs).sample() # 生成随机样本
fair_probs, counts / 1000

(tensor([0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667]),
 tensor([0.1430, 0.1670, 0.1730, 0.1880, 0.1540, 0.1750]))